[package]
name = "cd_subcode"
version = "0.1.0"
authors = ["The6P4C <watsonjcampbell@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crc16 = "0.4.0"
